name: Deploy to Railway (Production)

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Deploy to Railway
        run: railway up --service frontend --service backend --service db --ci
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 